# For YAML Formatting see https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
---
IdToNames:
  "E3:60:58:E1:90:E3": "Office Bedroom"
  "E3:60:59:21:24:B7": "Kai Bedroom"
  "E3:60:59:20:E4:B6": "LauraScott Bedroom"
  "E3:60:59:21:CC:FC": "TV Room"